name: todo_app 
description: "A beautiful to-do list app with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.jpg"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.jpg"
