// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhMNFI9q5IjVFnE9kzBsMn8YSUDVzLpg',
    appId: '1:187699490120:web:2b2e465ca1f6f0e65c577d',
    messagingSenderId: '187699490120',
    projectId: 'to-do-73104',
    authDomain: 'to-do-73104.firebaseapp.com',
    storageBucket: 'to-do-73104.firebasestorage.app',
    measurementId: 'G-CP0XHYCE7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL7g_uG0ObydTKtVhqIC23Z5Oy2x_AALY',
    appId: '1:187699490120:android:23ff8689d443c1435c577d',
    messagingSenderId: '187699490120',
    projectId: 'to-do-73104',
    storageBucket: 'to-do-73104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDldY_LlSGjJDYYnAXwllem0dYyVeHV8hU',
    appId: '1:187699490120:ios:c184522b82a86bb65c577d',
    messagingSenderId: '187699490120',
    projectId: 'to-do-73104',
    storageBucket: 'to-do-73104.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDldY_LlSGjJDYYnAXwllem0dYyVeHV8hU',
    appId: '1:187699490120:ios:c184522b82a86bb65c577d',
    messagingSenderId: '187699490120',
    projectId: 'to-do-73104',
    storageBucket: 'to-do-73104.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAhMNFI9q5IjVFnE9kzBsMn8YSUDVzLpg',
    appId: '1:187699490120:web:ad3f9760dd733ab15c577d',
    messagingSenderId: '187699490120',
    projectId: 'to-do-73104',
    authDomain: 'to-do-73104.firebaseapp.com',
    storageBucket: 'to-do-73104.firebasestorage.app',
    measurementId: 'G-1T624ZRF6W',
  );
}
